apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: subjectsphp
  namespace: tlson
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tlson.clemoregan.com`) && (PathPrefix(`/`))
      services:
        - name: subjectsphp
          port: 80
  tls: # This route uses TLS
    secretName: traefik-tls-cert
    options:
      name: ciphers

#   name: subjectsphp
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: HostSNI(`tlson.clemoregan.com`)
#     #kind: Rule
#     services:
#     - name: subjectsphp
#       port: 443
#   tls:
#     secretName: traefik-tls-cert
#     passthrough: true
