apiVersion: v1
kind: Service
metadata:
  name: {{ include "subjectsphp.fullname" . }}
  labels:
    {{- include "subjectsphp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: subjectsphp
  selector:
    {{- include "subjectsphp.selectorLabels" . | nindent 4 }}
